// GET CURRENTLY RANKING FOR
// USE LONG TERM STRATEGY + RANKING FOR + DESCRIPTION + LOCATION TO CREATE TOPIC LIST (with examples distinguish topics from keywords)
// CREATE A LIST OF 20 KEYWORDS FOR THE TOPIC AND ADD THE ONES WITH >0 LATEST SEARCH VOLUME TO THE KEYWORDS LIST
// FROM A LIST OF 10 POSSIBLE REASONS, MAKE AI PICK 4
// RUN A PERPLEXITY SCRIPT ON DATE RANGE AND TOPIC AREA TO GET 2 ARTICLES
// OF ALL KEYWORDS FOR ALL TOPICS PICK 6 TRENDING WITH LLM